stages:
  get-features:
    cmd: python3 scripts/data_scripts/get_features.py data/raw/train.csv
    deps:
    - data/raw/train.csv
    - scripts/data_scripts/get_features.py
    outs:
    - data/stage1
